### ISSUE TITLE
No alert after threshold is reached

### ISSUE THREAD

**Issue by JC1738** [scobal/seyren#300] opened 2015-05-12 21:44 UTC
I have set an alert, and the graphs show the metrics pass the warning and error level, but no alerts are actually triggered.  Any ideas what would cause this.  It's probably some config since this is the first alert on the setup.  Using docker mongo and the docker seyren containers.

![seyren 2015-05-12 14-41-24](https://cloud.githubusercontent.com/assets/3421783/7599244/44d4b04c-f8b5-11e4-8e5d-2e27b2a59cb1.jpg)

**Comment by JC1738** [comment] 2015-05-12 21:52
I do see the following in the logs, but graphs do show up:
```
 WARN   c.s.c.s.c.GraphiteTargetChecker - CG Admin CI 500 Errors failed to read from Graphite
 com.seyren.core.util.graphite.GraphiteReadException: Failed to read from Graphite
	at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:136) ~[seyren-core-1.2.1.jar:na]
	at com.seyren.core.service.checker.GraphiteTargetChecker.check(GraphiteTargetChecker.java:50) ~[seyren-core-1.2.1.jar:na]
	at com.seyren.core.service.schedule.CheckRunner.run(CheckRunner.java:65) [seyren-core-1.2.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@a045ecf; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2342) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:817) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697) ~[jackson-core-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3031) ~[jackson-databind-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978) ~[jackson-databind-2.3.2.jar:2.3.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1737) ~[jackson-databind-2.3.2.jar:2.3.2]
	at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:37) ~[seyren-core-1.2.1.jar:na]
	at com.seyren.core.service.checker.JsonNodeResponseHandler.handleResponse(JsonNodeResponseHandler.java:28) ~[seyren-core-1.2.1.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[httpclient-4.3.3.jar:4.3.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.3.jar:4.3.3]
	at com.seyren.core.util.graphite.GraphiteHttpClient.getTargetJson(GraphiteHttpClient.java:134) ~[seyren-core-1.2.1.jar:na]
	... 9 common frames omitted
root@675b2f828bb6:/# 
```

**Comment by JC1738** [comment] 2015-05-13 23:52
Determined the problem:

```
This causes error above:
alias(summarize(statsd.counters.service.request.status_code.500.count, "10min"), "500 alerts")

This same query does not:
alias(summarize(statsd.counters.service.request.status_code.500.count, '10min'), '500 alerts')
```

Doesn't like the double quote.  The sad/frustrating thing is that the graphs actually show on both, it just silently logs these errors and won't alert when you use the double quote.

**Comment by scobal** [comment] 2016-05-01 20:13
Duplicate of 256

**Closed by scobal** 2016-05-01 20:13 UTC
