### ISSUE TITLE
Add ability to group checks on the UI

### ISSUE THREAD

**Issue by sergey-brutsky** [scobal/seyren#301] opened 2015-05-13 14:27 UTC
It would be nice to have a feature to group check somehow.
Now we have a lot of checks in a table and it's extremely hard to find necessary.

Is it possible to add something like "grouping" of checks or "tagging" ?
So we could easily navigate to group and to necessary check

Thanks

**Comment by scobal** [comment] 2016-05-03 20:31
Duplicate of #198 (I think)

**Closed by scobal** 2016-05-03 20:31 UTC
